swagger: "2.0"
info:
  title: ACC REST API Documentation
  description: "This API enables to use the plain-text ERP tool Acc via an RESTful interface."
  contact:
    name: 72nd
    url: https://github.com/72nd
    email: msg@frg72.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.5.2
basePath: "/v1"
schemes:
  - https
paths:
  /customers:
    get:
      summary: Get all customers
      description: Returns an Array of all customers
      produces:
        - application/json
      responses:
        200:
          description: Customers
          schema:
            $ref: 'parties.yaml#/Parties'


