openapi: 3.0.0
info:
  title: ACC REST API Documentation
  description: "This API enables to use the plain-text ERP tool Acc via an RESTful interface."
  contact:
    name: 72nd
    url: https://github.com/72nd
    email: msg@frg72.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.5.2
basePath: "/v1"
schemes:
  - https
tags:
  - name: customer
    x-displayName: Customers
    description: Someone who buys stuff from your company.
  - name: employee
    x-displayName: Employees
    description: Someone who works for you.
  - name: expense
    x-displayName: Expenses
    description: Represents a payment done by the company or a third party to assure the ongoing of the business.
  - name: invoice
    x-displayName: Invoices
    description: Interact with your invoices.
  - name: misc_document
    x-displayName: Miscellaneous Records
    description: "Business records which are not invoices or expenses but still important for accounting. Example: A credit note from an insurance."
  - name: project
    x-displayName: Projects
    description: A project for a customer.
  - name: statement
    x-displayName: Statements
    description: A bank statement containing transactions on a bank account.
  - name: expense_model
    x-displayName: Expense Model
    description: |
      # Expenses
      <SchemaDefinition schemaRef="#/models/expenses" />

      # Expense
      <SchemaDefinition schemaRef="#/models/expense" />

  - name: invoice_model
    x-displayName: Invoice Model
    description: |
      # Invoices
     
      <SchemaDefinition schemaRef="#/models/invoices" />

      # Invoice
      <SchemaDefinition schemaRef="#/models/invoice" />

  - name: misc_document_model
    x-displayName: Miscellaneous Records Model
    description: 
  - name: party_model
    x-displayName: Party Model (Customer, Employee)
    description: |
      # Parties
      <SchemaDefinition schemaRef="#/models/parties" />

      # Party
      <SchemaDefinition schemaRef="#/models/party" />
  - name: project_model
    x-displayName: Project Model
    description: 
  - name: statement_model
    x-displayName: Bank Statement Model
    description: 
  - name: transaction_model
    x-displayName: Transaction Model
    description: 
x-tagGroups:
  - name: API
    tags:
      - customer
      - employee
      - expense
      - invoice
      - misc_document
      - project
      - statement
  - name: Models
    tags:
      - expense_model
      - invoice_model
      - misc_document_model
      - party_model
      - project_model
      - statement_model
      - transaction_model
paths:
  /customers:
    $ref: 'parties.yaml#/paths/customers'
  /customers/{id}:
    $ref: 'parties.yaml#/paths/customerById'
  /employees:
    $ref: 'parties.yaml#/paths/employees'
  /expenses:
    $ref: 'expenses.yaml#/paths/expenses'
  /expenses/{id}:
    $ref: 'expenses.yaml#/paths/expenseById'
  /invoices:
    $ref: 'invoices.yaml#/paths/invoices'
  /invoices/{id}:
    $ref: 'invoices.yaml#/paths/invoiceById'
models:
  parties:
    $ref: 'parties.yaml#/schemas/parties'
  party:
    $ref: 'parties.yaml#/schemas/party'
  expenses:
    $ref: 'expenses.yaml#/schemas/expenses'
  expense:
    $ref: 'expenses.yaml#/schemas/expense'
  invoices:
    $ref: 'invoices.yaml#/schemas/invoices'
  invoice:
    $ref: 'invoices.yaml#/schemas/invoice'
