openapi: 3.0.0
info:
  title: ACC REST API Documentation
  description: "This API enables to use the plain-text ERP tool Acc via an RESTful interface."
  contact:
    name: 72nd
    url: https://github.com/72nd
    email: msg@frg72.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.5.2
basePath: "/v1"
schemes:
  - https
tags:
  - name: customer
    x-displayName: Customers
    description: Someone who buys stuff from your company.
  - name: employee
    x-displayName: Employees
    description: Someone who works for you.
  - name: expense
    x-displayName: Expenses
    description: Represents a payment done by the company or a third party to assure the ongoing of the business.
  - name: invoice
    x-displayName: Invoices
    description: Interact with your invoices.
  - name: misc_document
    x-displayName: Miscellaneous Records
    description: "Business records which are not invoices or expenses but still important for accounting. Example: A credit note from an insurance."
  - name: project
    x-displayName: Projects
    description: A project for a customer.
  - name: statement
    x-displayName: Statements
    description: A bank statement containing transactions on a bank account.
  - name: customer_model
    x-displayName: Customer Model
    description: |
      ## Parties
      <SchemaDefinition schemaRef="#/models/parties" />

      ## Party
      <SchemaDefinition schemaRef="#/models/party" />
  - name: employee_model
    x-displayName: Employee Model
    description: 
  - name: expense_model
    x-displayName: Expense Model
    description: 
  - name: invoice_model
    x-displayName: Invoice Model
    description: An invoice sent to a customer for some services
  - name: misc_document_model
    x-displayName: Miscellaneous Records Model
    description: 
  - name: project_model
    x-displayName: Project Model
    description: 
  - name: statement_model
    x-displayName: Bank Statement Model
    description: 
  - name: transaction_model
    x-displayName: Transaction Model
    description: 
x-tagGroups:
  - name: API
    tags:
      - customer
      - employee
      - expense
      - invoice
      - misc_document
      - project
      - statement
  - name: Models
    tags:
      - customer_model
      - employee_model
      - expense_model
      - invoice_model
      - misc_document_model
      - project_model
      - statement_model
      - transaction_model
paths:
  $ref: 'parties.yaml#/paths'
models:
  parties:
    $ref: 'parties.yaml#/schemas/parties'
  party:
    $ref: 'parties.yaml#/schemas/party'
